//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public int jobID { get; set; }
        public Nullable<int> userId { get; set; }
        public string compName { get; set; }
        public string jobCategory { get; set; }
        public string jobTitle { get; set; }
        public Nullable<int> currentOpenings { get; set; }
        public Nullable<System.DateTime> joiningDate { get; set; }
        public string location { get; set; }
        public string designation { get; set; }
        public Nullable<int> experience { get; set; }
        public string qualification { get; set; }
        public string skillSet { get; set; }
        public string contactDetails { get; set; }
    
        public virtual User User { get; set; }
    }
}
