//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JobSeeker
    {
        public int jobSeekerID { get; set; }
        public Nullable<int> userId { get; set; }
        public string address { get; set; }
        [Required]
        [Range(0,40)]
        public Nullable<int> experience { get; set; }
        [Required]
        public string qualification { get; set; }
        [Required]
        public string profession { get; set; }
        [Required]
        public string skillset { get; set; }
        [Required]
        public string resume { get; set; }
    
        public virtual User User { get; set; }
    }
}
